# Generated by Django 5.2.9 on 2025-12-16 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('license', '0003_auto_20251115_0737'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='license',
            name='aadhar_number',
        ),
        migrations.RemoveField(
            model_name='license',
            name='name',
        ),
        migrations.AddField(
            model_name='license',
            name='age',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='license',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='license',
            name='full_name',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='license',
            name='gender',
            field=models.CharField(blank=True, choices=[('male', 'Aan'), ('female', 'Pen'), ('other', 'Other')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='license',
            name='ward_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='license',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='license',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='volunteers/photos/'),
        ),
    ]
