# Generated by Django 5.2.9 on 2025-12-16 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('license', '0004_remove_license_aadhar_number_remove_license_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='license',
            name='areas_of_interest',
            field=models.TextField(blank=True, help_text='Education, Health, Food Distribution, etc.', null=True),
        ),
        migrations.AddField(
            model_name='license',
            name='availability',
            field=models.CharField(blank=True, help_text='Days / times available', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='license',
            name='blood_group',
            field=models.CharField(blank=True, choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('O+', 'O+'), ('O-', 'O-'), ('AB+', 'AB+'), ('AB-', 'AB-')], max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='license',
            name='emergency_contact_name',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='license',
            name='emergency_contact_phone',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='license',
            name='heard_from',
            field=models.CharField(blank=True, help_text='How did you hear about us', max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='license',
            name='license_pdf',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='license',
            name='previous_experience',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='license',
            name='role',
            field=models.CharField(blank=True, choices=[('field_volunteer', 'Field Volunteer'), ('event_helper', 'Event Helper'), ('office_support', 'Office Support'), ('other', 'Other')], max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='license',
            name='signature',
            field=models.CharField(blank=True, help_text='Signed name or digital signature', max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='license',
            name='valid_till',
            field=models.DateField(blank=True, help_text='Membership validity date', null=True),
        ),
        migrations.AlterField(
            model_name='license',
            name='full_name',
            field=models.CharField(default='Unknown', max_length=150),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='license',
            name='gender',
            field=models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='license',
            name='ward_number',
            field=models.CharField(default='Unknown', max_length=20),
            preserve_default=False,
        ),
    ]
