# Generated by Django 3.1.12 on 2026-02-14 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('license', '0005_license_areas_of_interest_license_availability_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='license',
            name='volunteer_id',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='license',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
