# Generated by Django 3.1.12 on 2026-03-24 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('license', '0006_auto_20260214_1718'),
    ]

    operations = [
        migrations.AlterField(
            model_name='license',
            name='ward_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
