# Generated by Django 3.1.12 on 2026-03-24 07:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('license', '0007_auto_20260324_1157'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='license',
            name='signature',
        ),
    ]
