# Generated by Django 3.1.12 on 2026-03-26 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('license', '0008_remove_license_signature'),
    ]

    operations = [
        migrations.AlterField(
            model_name='license',
            name='gender',
            field=models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female'), ('third_gender', 'Third Gender')], max_length=20, null=True),
        ),
    ]
